from sklearn import datasets
import pandas as pd
import matplotlib.pyplot as plt
dados = datasets.load_wine()

df = dados.data

df = pd.DataFrame(df)
df.columns = dados.feature_names

df['target'] = dados.target

df_0 = df.loc[df['target']==0]
df_1 = df.loc[df['target']==1]
df_2 = df.loc[df['target']==2]

for i in df.columns[:4]:
    for j in df.columns[:4]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[i],df_0[j],label=dados.target_names[0])
        plt.scatter(df_1[i],df_1[j],label=dados.target_names[1])
        plt.scatter(df_2[i],df_2[j],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(i)
        plt.ylabel(j)
        plt.title(i+' x '+j)
        
for a in df.columns[:3]:
    for b in df.columns[:3]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[a],df_0[b],label=dados.target_names[0])
        plt.scatter(df_1[a],df_1[b],label=dados.target_names[1])
        plt.scatter(df_2[a],df_2[b],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(a)
        plt.ylabel(b)
        plt.title(a+' x '+b)

for c in df.columns[:2]:
    for d in df.columns[:2]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[c],df_0[d],label=dados.target_names[0])
        plt.scatter(df_1[c],df_1[d],label=dados.target_names[1])
        plt.scatter(df_2[c],df_2[d],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(c)
        plt.ylabel(d)
        plt.title(c+' x '+d)
        
for e in df.columns[:1]:
    for f in df.columns[:1]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[e],df_0[f],label=dados.target_names[0])
        plt.scatter(df_1[e],df_1[f],label=dados.target_names[1])
        plt.scatter(df_2[e],df_2[f],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(e)
        plt.ylabel(f)
        plt.title(e+' x '+f)
        
for g in df.columns[:5]:
    for h in df.columns[:5]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[g],df_0[h],label=dados.target_names[0])
        plt.scatter(df_1[g],df_1[h],label=dados.target_names[1])
        plt.scatter(df_2[g],df_2[h],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(g)
        plt.ylabel(h)
        plt.title(g+' x '+h)
        
for i in df.columns[:6]:
    for j in df.columns[:6]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[i],df_0[j],label=dados.target_names[0])
        plt.scatter(df_1[i],df_1[j],label=dados.target_names[1])
        plt.scatter(df_2[i],df_2[j],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(i)
        plt.ylabel(j)
        plt.title(i+' x '+j)
        
for k in df.columns[:7]:
    for l in df.columns[:7]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[k],df_0[l],label=dados.target_names[0])
        plt.scatter(df_1[k],df_1[l],label=dados.target_names[1])
        plt.scatter(df_2[k],df_2[l],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(k)
        plt.ylabel(l)
        plt.title(k+' x '+l)
        
for m in df.columns[:8]:
    for n in df.columns[:8]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[m],df_0[n],label=dados.target_names[0])
        plt.scatter(df_1[m],df_1[n],label=dados.target_names[1])
        plt.scatter(df_2[m],df_2[n],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(m)
        plt.ylabel(n)
        plt.title(m+' x '+n)
        
for o in df.columns[:9]:
    for p in df.columns[:9]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[o],df_0[p],label=dados.target_names[0])
        plt.scatter(df_1[o],df_1[p],label=dados.target_names[1])
        plt.scatter(df_2[o],df_2[p],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(o)
        plt.ylabel(p)
        plt.title(o+' x '+p)
        
for q in df.columns[:10]:
    for r in df.columns[:10]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[q],df_0[r],label=dados.target_names[0])
        plt.scatter(df_1[q],df_1[r],label=dados.target_names[1])
        plt.scatter(df_2[q],df_2[r],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(q)
        plt.ylabel(r)
        plt.title(q+' x '+r)
        
for s in df.columns[:11]:
    for t in df.columns[:11]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[s],df_0[t],label=dados.target_names[0])
        plt.scatter(df_1[s],df_1[t],label=dados.target_names[1])
        plt.scatter(df_2[s],df_2[t],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(s)
        plt.ylabel(t)
        plt.title(s+' x '+t)
        
for u in df.columns[:12]:
    for v in df.columns[:12]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[u],df_0[v],label=dados.target_names[0])
        plt.scatter(df_1[u],df_1[v],label=dados.target_names[1])
        plt.scatter(df_2[u],df_2[v],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(u)
        plt.ylabel(v)
        plt.title(u+' x '+v)

for w in df.columns[:13]:
    for x in df.columns[:13]:
        plt.figure(figsize=(8,4))
        plt.scatter(df_0[w],df_0[x],label=dados.target_names[0])
        plt.scatter(df_1[w],df_1[x],label=dados.target_names[1])
        plt.scatter(df_2[w],df_2[x],label=dados.target_names[2])
        plt.legend()
        plt.xlabel(w)
        plt.ylabel(x)
        plt.title(w+' x '+x)
        

    
plt.figure()
plt.hist(df_0[a],bins=20,label=dados.target_names[0])
plt.hist(df_1[a],bins=20,label=dados.target_names[1])
plt.hist(df_2[a],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('ash das bebidas')

plt.figure()
plt.hist(df_0[e],bins=20,label=dados.target_names[0])
plt.hist(df_1[e],bins=20,label=dados.target_names[1])
plt.hist(df_2[e],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('alcohol das bebidas')

plt.figure()
plt.hist(df_0[c],bins=20,label=dados.target_names[0])
plt.hist(df_1[c],bins=20,label=dados.target_names[1])
plt.hist(df_2[c],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('malic_acid das bebidas')

plt.figure()
plt.hist(df_0[g],bins=20,label=dados.target_names[0])
plt.hist(df_1[g],bins=20,label=dados.target_names[1])
plt.hist(df_2[g],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('magnesium das bebidas')
        
plt.figure()
plt.hist(df_0[i],bins=20,label=dados.target_names[0])
plt.hist(df_1[i],bins=20,label=dados.target_names[1])
plt.hist(df_2[i],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('total_phenols das bebidas')

plt.figure()
plt.hist(df_0[k],bins=20,label=dados.target_names[0])
plt.hist(df_1[k],bins=20,label=dados.target_names[1])
plt.hist(df_2[k],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('flavinoids das bebidas')

plt.figure()
plt.hist(df_0[m],bins=20,label=dados.target_names[0])
plt.hist(df_1[m],bins=20,label=dados.target_names[1])
plt.hist(df_2[m],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('noflavanoid_phenols das bebidas')

plt.figure()
plt.hist(df_0[o],bins=20,label=dados.target_names[0])
plt.hist(df_1[o],bins=20,label=dados.target_names[1])
plt.hist(df_2[o],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('proanthocyanins das bebidas')

plt.figure()
plt.hist(df_0[q],bins=20,label=dados.target_names[0])
plt.hist(df_1[q],bins=20,label=dados.target_names[1])
plt.hist(df_2[q],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('color_intensity das bebidas')

plt.figure()
plt.hist(df_0[s],bins=20,label=dados.target_names[0])
plt.hist(df_1[s],bins=20,label=dados.target_names[1])
plt.hist(df_2[s],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('hue das bebidas')

plt.figure()
plt.hist(df_0[u],bins=20,label=dados.target_names[0])
plt.hist(df_1[u],bins=20,label=dados.target_names[1])
plt.hist(df_2[u],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('od280/od315_of_diluted_wines das bebidas')

plt.figure()
plt.hist(df_0[w],bins=20,label=dados.target_names[0])
plt.hist(df_1[w],bins=20,label=dados.target_names[1])
plt.hist(df_2[w],bins=20,label=dados.target_names[2])
plt.legend()
plt.title('proline das bebidas')

plt.figure()
df_0.hist(column='ash', bins=100)
plt.title('ash da bebida 0')
plt.figure()
df_0.hist(column='malic_acid', bins=100)
plt.title('malid_acid da bebida 0')
plt.figure()
df_0.hist(column='alcohol', bins=100)
plt.title('alcohol da bebida 0')
plt.figure()
df_0.hist(column='magnesium', bins=100)
plt.title('magnesium da bebida 0')
plt.figure()
df_0.hist(column='nonflavanoid_phenols', bins=100)
plt.title('nonflavanoid_phenols da bebida 0')       
plt.figure()
df_0.hist(column='proanthocyanins', bins=100)
plt.title('proanthocyanins da bebida 0')  
plt.figure()
df_0.hist(column='color_intensity', bins=100)
plt.title('color_intensity da bebida 0')
plt.figure()
df_0.hist(column='hue', bins=100)
plt.title('hue da bebida 0')
plt.figure()
df_0.hist(column='od280/od315_of_diluted_wines', bins=100)
plt.title('od280/od315_of_diluted_wines da bebida 0')
plt.figure()
df_0.hist(column='proline', bins=100)
plt.title('proline da bebida 0')

plt.figure()
df_1.hist(column='ash', bins=100)
plt.title('ash da bebida 1')
plt.figure()
df_1.hist(column='malic_acid', bins=100)
plt.title('malid_acid da bebida 1')
plt.figure()
df_1.hist(column='alcohol', bins=100)
plt.title('alcohol da bebida 1')
plt.figure()
df_1.hist(column='magnesium', bins=100)
plt.title('magnesium da bebida 1')
plt.figure()
df_1.hist(column='nonflavanoid_phenols', bins=100)
plt.title('nonflavanoid_phenols da bebida 1')       
plt.figure()
df_1.hist(column='proanthocyanins', bins=100)
plt.title('proanthocyanins da bebida 1')  
plt.figure()
df_1.hist(column='color_intensity', bins=100)
plt.title('color_intensity da bebida 1')
plt.figure()
df_1.hist(column='hue', bins=100)
plt.title('hue da bebida 1')
plt.figure()
df_1.hist(column='od280/od315_of_diluted_wines', bins=100)
plt.title('od280/od315_of_diluted_wines da bebida 1')
plt.figure()
df_1.hist(column='proline', bins=100)
plt.title('proline da bebida 1')

plt.figure()
df_2.hist(column='ash', bins=100)
plt.title('ash da bebida 2')
plt.figure()
df_2.hist(column='malic_acid', bins=100)
plt.title('malid_acid da bebida 2')
plt.figure()
df_2.hist(column='alcohol', bins=100)
plt.title('alcohol da bebida 2')
plt.figure()
df_2.hist(column='magnesium', bins=100)
plt.title('magnesium da bebida 2')
plt.figure()
df_2.hist(column='nonflavanoid_phenols', bins=100)
plt.title('nonflavanoid_phenols da bebida 2')       
plt.figure()
df_2.hist(column='proanthocyanins', bins=100)
plt.title('proanthocyanins da bebida 2')  
plt.figure()
df_2.hist(column='color_intensity', bins=100)
plt.title('color_intensity da bebida 2')
plt.figure()
df_2.hist(column='hue', bins=100)
plt.title('hue da bebida 2')
plt.figure()
df_2.hist(column='od280/od315_of_diluted_wines', bins=100)
plt.title('od280/od315_of_diluted_wines da bebida 2')
plt.figure()
df_2.hist(column='proline', bins=100)
plt.title('proline da bebida 2')

plt.figure()
df.boxplot(column='ash')
plt.title('ash das bebidas')
plt.figure()
df.boxplot(column='malic_acid')
plt.title('malid_acid das bebidas')
plt.figure()
df.boxplot(column='alcohol')
plt.title('alcohol das bebidas')
plt.figure()
df.boxplot(column='magnesium')
plt.title('magnesium das bebida ')
plt.figure()
df.boxplot(column='nonflavanoid_phenols')
plt.title('nonflavanoid_phenols das bebidas')       
plt.figure()
df.boxplot(column='proanthocyanins')
plt.title('proanthocyanins das bebidas')  
plt.figure()
df.boxplot(column='color_intensity')
plt.title('color_intensity das bebidas')
plt.figure()
df.boxplot(column='hue')
plt.title('hue das bebidas')
plt.figure()
df.boxplot(column='od280/od315_of_diluted_wines')
plt.title('od280/od315_of_diluted_wines das bebidas')
plt.figure()
df.boxplot(column='proline',)
plt.title('proline das bebidas')

plt.figure()
df_0.boxplot(column='ash')
plt.title('ash da bebida 0')
plt.figure()
df_0.boxplot(column='malic_acid')
plt.title('malid_acid da bebida 0')
plt.figure()
df_0.boxplot(column='alcohol')
plt.title('alcohol da bebida 0')
plt.figure()
df_0.boxplot(column='magnesium')
plt.title('magnesium da bebida 0')
plt.figure()
df_0.boxplot(column='nonflavanoid_phenols')
plt.title('nonflavanoid_phenols da bebida 0')       
plt.figure()
df_0.boxplot(column='proanthocyanins')
plt.title('proanthocyanins da bebida 0')  
plt.figure()
df_0.boxplot(column='color_intensity')
plt.title('color_intensity da bebida 0')
plt.figure()
df_0.boxplot(column='hue')
plt.title('hue da bebida 0')
plt.figure()
df_0.boxplot(column='od280/od315_of_diluted_wines')
plt.title('od280/od315_of_diluted_wines da bebida 0')
plt.figure()
df_0.boxplot(column='proline')
plt.title('proline da bebida 0')

plt.figure()
df_1.boxplot(column='ash')
plt.title('ash da bebida 1')
plt.figure()
df_1.boxplot(column='malic_acid')
plt.title('malid_acid da bebida 1')
plt.figure()
df_1.boxplot(column='alcohol')
plt.title('alcohol da bebida 1')
plt.figure()
df_1.boxplot(column='magnesium')
plt.title('magnesium da bebida 1')
plt.figure()
df_1.boxplot(column='nonflavanoid_phenols')
plt.title('nonflavanoid_phenols da bebida 1')       
plt.figure()
df_1.boxplot(column='proanthocyanins')
plt.title('proanthocyanins da bebida 1')  
plt.figure()
df_1.boxplot(column='color_intensity')
plt.title('color_intensity da bebida 1')
plt.figure()
df_1.boxplot(column='hue')
plt.title('hue da bebida 1')
plt.figure()
df_1.boxplot(column='od280/od315_of_diluted_wines')
plt.title('od280/od315_of_diluted_wines da bebida 1')
plt.figure()
df_1.boxplot(column='proline')
plt.title('proline da bebida 1')

plt.figure()
df_2.boxplot(column='ash')
plt.title('ash da bebida 2')
plt.figure()
df_2.boxplot(column='malic_acid')
plt.title('malid_acid da bebida 2')
plt.figure()
df_2.boxplot(column='alcohol')
plt.title('alcohol da bebida 2')
plt.figure()
df_2.boxplot(column='magnesium')
plt.title('magnesium da bebida 2')
plt.figure()
df_2.boxplot(column='nonflavanoid_phenols')
plt.title('nonflavanoid_phenols da bebida 2')       
plt.figure()
df_2.boxplot(column='proanthocyanins')
plt.title('proanthocyanins da bebida 2')  
plt.figure()
df_2.boxplot(column='color_intensity')
plt.title('color_intensity da bebida 2')
plt.figure()
df_2.boxplot(column='hue')
plt.title('hue da bebida 2')
plt.figure()
df_2.boxplot(column='od280/od315_of_diluted_wines')
plt.title('od280/od315_of_diluted_wines da bebida 2')
plt.figure()
df_2.boxplot(column='proline')
plt.title('proline da bebida 2')





plt.figure()
plt.plot(df_0[a],label=dados.target_names[0])
plt.plot(df_1[a],label=dados.target_names[1])
plt.plot(df_2[a],label=dados.target_names[2])
plt.legend()
plt.title('ash das bebidas')

plt.figure()
plt.plot(df_0[e],label=dados.target_names[0])
plt.plot(df_1[e],label=dados.target_names[1])
plt.plot(df_2[e],label=dados.target_names[2])
plt.legend()
plt.title('alcohol das bebidas')

plt.figure()
plt.plot(df_0[c],label=dados.target_names[0])
plt.plot(df_1[c],label=dados.target_names[1])
plt.plot(df_2[c],label=dados.target_names[2])
plt.legend()
plt.title('malic_acid das bebidas')

plt.figure()
plt.plot(df_0[g],label=dados.target_names[0])
plt.plot(df_1[g],label=dados.target_names[1])
plt.plot(df_2[g],label=dados.target_names[2])
plt.legend()
plt.title('magnesium das bebidas')
        
plt.figure()
plt.plot(df_0[i],label=dados.target_names[0])
plt.plot(df_1[i],label=dados.target_names[1])
plt.plot(df_2[i],label=dados.target_names[2])
plt.legend()
plt.title('total_phenols das bebidas')

plt.figure()
plt.plot(df_0[k],label=dados.target_names[0])
plt.plot(df_1[k],label=dados.target_names[1])
plt.plot(df_2[k],label=dados.target_names[2])
plt.legend()
plt.title('flavinoids das bebidas')

plt.figure()
plt.plot(df_0[m],label=dados.target_names[0])
plt.plot(df_1[m],label=dados.target_names[1])
plt.plot(df_2[m],label=dados.target_names[2])
plt.legend()
plt.title('noflavanoid_phenols das bebidas')

plt.figure()
plt.plot(df_0[o],label=dados.target_names[0])
plt.plot(df_1[o],label=dados.target_names[1])
plt.plot(df_2[o],label=dados.target_names[2])
plt.legend()
plt.title('proanthocyanins das bebidas')

plt.figure()
plt.plot(df_0[q],label=dados.target_names[0])
plt.plot(df_1[q],label=dados.target_names[1])
plt.plot(df_2[q],label=dados.target_names[2])
plt.legend()
plt.title('color_intensity das bebidas')

plt.figure()
plt.plot(df_0[s],label=dados.target_names[0])
plt.plot(df_1[s],label=dados.target_names[1])
plt.plot(df_2[s],label=dados.target_names[2])
plt.legend()
plt.title('hue das bebidas')

plt.figure()
plt.plot(df_0[u],label=dados.target_names[0])
plt.plot(df_1[u],label=dados.target_names[1])
plt.plot(df_2[u],label=dados.target_names[2])
plt.legend()
plt.title('od280/od315_of_diluted_wines das bebidas')

plt.figure()
plt.plot(df_0[w],label=dados.target_names[0])
plt.plot(df_1[w],label=dados.target_names[1])
plt.plot(df_2[w],label=dados.target_names[2])
plt.legend()
plt.title('proline das bebidas')

plt.figure()
df_0.plot(column='ash')
plt.title('ash da bebida 0')
plt.figure()
df_0.plot(column='malic_acid')
plt.title('malid_acid da bebida 0')
plt.figure()
df_0.plot(column='alcohol')
plt.title('alcohol da bebida 0')
plt.figure()
df_0.plot(column='magnesium')
plt.title('magnesium da bebida 0')
plt.figure()
df_0.plot(column='nonflavanoid_phenols')
plt.title('nonflavanoid_phenols da bebida 0')       
plt.figure()
df_0.plot(column='proanthocyanins')
plt.title('proanthocyanins da bebida 0')  
plt.figure()
df_0.plot(column='color_intensity')
plt.title('color_intensity da bebida 0')
plt.figure()
df_0.plot(column='hue')
plt.title('hue da bebida 0')
plt.figure()
df_0.plot(column='od280/od315_of_diluted_wines')
plt.title('od280/od315_of_diluted_wines da bebida 0')
plt.figure()
df_0.plot(column='proline')
plt.title('proline da bebida 0')

plt.figure()
df_1.plot(column='ash')
plt.title('ash da bebida 1')
plt.figure()
df_1.plot(column='malic_acid')
plt.title('malid_acid da bebida 1')
plt.figure()
df_1.plot(column='alcohol')
plt.title('alcohol da bebida 1')
plt.figure()
df_1.plot(column='magnesium')
plt.title('magnesium da bebida 1')
plt.figure()
df_1.plot(column='nonflavanoid_phenols')
plt.title('nonflavanoid_phenols da bebida 1')       
plt.figure()
df_1.plot(column='proanthocyanins')
plt.title('proanthocyanins da bebida 1')  
plt.figure()
df_1.plot(column='color_intensity')
plt.title('color_intensity da bebida 1')
plt.figure()
df_1.plot(column='hue')
plt.title('hue da bebida 1')
plt.figure()
df_1.plot(column='od280/od315_of_diluted_wines')
plt.title('od280/od315_of_diluted_wines da bebida 1')
plt.figure()
df_1.plot(column='proline')
plt.title('proline da bebida 1')

plt.figure()
df_2.plot(column='ash')
plt.title('ash da bebida 2')
plt.figure()
df_2.plot(column='malic_acid')
plt.title('malid_acid da bebida 2')
plt.figure()
df_2.plot(column='alcohol')
plt.title('alcohol da bebida 2')
plt.figure()
df_2.plot(column='magnesium')
plt.title('magnesium da bebida 2')
plt.figure()
df_2.plot(column='nonflavanoid_phenols')
plt.title('nonflavanoid_phenols da bebida 2')       
plt.figure()
df_2.plot(column='proanthocyanins')
plt.title('proanthocyanins da bebida 2')  
plt.figure()
df_2.plot(column='color_intensity')
plt.title('color_intensity da bebida 2')
plt.figure()
df_2.plot(column='hue')
plt.title('hue da bebida 2')
plt.figure()
df_2.plot(column='od280/od315_of_diluted_wines')
plt.title('od280/od315_of_diluted_wines da bebida 2')
plt.figure()
df_2.plot(column='proline')
plt.title('proline da bebida 2')